export const enum Keyword {
    And = "and",
    As = "as",
    Each = "each",
    Else = "else",
    Error = "error",
    False = "false",
    HashBinary = "#binary",
    HashDate = "#date",
    HashDateTime = "#datetime",
    HashDateTimeZone = "#datetimezone",
    HashDuration = "#duration",
    HashInfinity = "#infinity",
    HashNan = "#nan",
    HashSections = "#sections",
    HashShared = "#shared",
    HashTable = "#table",
    HashTime = "#time",
    If = "if",
    In = "in",
    Is = "is",
    Let = "let",
    Meta = "meta",
    Not = "not",
    Or = "or",
    Otherwise = "otherwise",
    Section = "section",
    Sections = "sections",
    Shared = "shared",
    Then = "then",
    True = "true",
    Try = "try",
    Type = "type",
}

export const Keywords: string[] = [
    Keyword.And,
    Keyword.As,
    Keyword.Each,
    Keyword.Else,
    Keyword.Error,
    Keyword.False,
    Keyword.HashBinary,
    Keyword.HashDate,
    Keyword.HashDateTime,
    Keyword.HashDateTimeZone,
    Keyword.HashDuration,
    Keyword.HashInfinity,
    Keyword.HashNan,
    Keyword.HashSections,
    Keyword.HashShared,
    Keyword.HashTable,
    Keyword.HashTime,
    Keyword.If,
    Keyword.In,
    Keyword.Is,
    Keyword.Let,
    Keyword.Meta,
    Keyword.Not,
    Keyword.Or,
    Keyword.Otherwise,
    Keyword.Section,
    Keyword.Sections,
    Keyword.Shared,
    Keyword.Then,
    Keyword.True,
    Keyword.Try,
    Keyword.Type,
];
