name: Gated pull request
on:
    workflow_dispatch:
    pull_request:
        branches: [master]
jobs:
    build-and-test:
        runs-on: windows-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4.1.2
            - name: setup node
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: "18.17"
            - run: node -v
            - run: npm ci
            - run: npm audit
            - run: npm run build
            - run: npm run test
